---
- name: Add Elasticsearch GPG key.
  become: yes
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana repository.
  become: yes
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0644
